### ISSUE TITLE
Uncaught Error: Cannot find module '../config'

### ISSUE THREAD

**Issue by shemerey** [Morosko/atom-telegram#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-telegram](https://github.com/Morosko/atom-telegram) package, v0.1.0

### Stack Trace

Uncaught Error: Cannot find module '../config'

```
At module.js:338

Error: Cannot find module '../config'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Users/zork/.atom/packages/atom-telegram/lib/helpers/telegram-login.coffee:21:29
    at exports.allowUnsafeEval (/Users/zork/.atom/packages/atom-telegram/node_modules/loophole/lib/loophole.js:14:14)
    at Object.<anonymous> (/Users/zork/.atom/packages/atom-telegram/lib/helpers/telegram-login.coffee:21:10)
    at Object.<anonymous> (/Users/zork/.atom/packages/atom-telegram/lib/helpers/telegram-login.coffee:19:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/zork/.atom/packages/atom-telegram/lib/state-controller.coffee:5:17)
    at Object.<anonymous> (/Users/zork/.atom/packages/atom-telegram/lib/state-controller.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/zork/.atom/packages/atom-telegram/lib/atom-telegram.coffee:2:19)
    at Object.<anonymous> (/Users/zork/.atom/packages/atom-telegram/lib/atom-telegram.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:19)
    at PackageDetailView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:269:22
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:262:83)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:32.3.0 settings-view:open (atom-pane.pane.active)
     -0:29.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:29.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "about",
      "archive-view",
      "autosave",
      "dev-live-reload",
      "welcome",
      "minimap",
      "tree-view"
    ],
    "packagesWithKeymapsDisabled": [
      "tool-bar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
esc2, v0.0.0
file-icons, v1.6.13
last-cursor-position, v0.9.0
project-manager, v2.6.5
symbol-gen, v1.0.0
synced-sidebar, v0.4.3
tool-bar, v0.1.9
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by shemerey** [comment]
@Morosko looks like config file is missing, can you post an example ?

**Comment by Morosko** [comment]
@shemerey Thanks for reporting. I'm sorry I've forgotten to add it again. Had removed it while testing.

The file `config.coffee` should be in `atom-telegram/lib` and look like this:

    exports.telegram = {
        prod: {
            app: {
                 id: 22622,
                hash: 'e1f0081e9656e619b72e417c45485236'
                version: '0.0.1'
                lang: 'en'
            },
            primaryDataCenter: {
                host: "149.154.167.91"
                port: "443"
            },
            files: {
                auth: '.authKey'
                userInformation: '.userInformation'
            }
        }
    };

**Comment by shemerey** [comment]
@Morosko that works thx, but I am getting a new one https://github.com/Morosko/atom-telegram/issues/2,  looks like something with `telegram.link`
