### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nonce' of undefined

### ISSUE THREAD

**Issue by shemerey** [Morosko/atom-telegram#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-telegram](https://github.com/Morosko/atom-telegram) package, v0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'nonce' of undefined

```
At /Users/zork/Projects/Atom/atom-telegram/node_modules/telegram.link/node_modules/telegram-mt-node/lib/auth/request-pq.js:36

TypeError: Cannot read property 'nonce' of undefined
    at mtproto.service.req_pq.callback (/Users/zork/Projects/Atom/atom-telegram/node_modules/telegram.link/node_modules/telegram-mt-node/lib/auth/request-pq.js:36:38)
    at /Users/zork/Projects/Atom/atom-telegram/node_modules/telegram.link/node_modules/telegram-mt-node/lib/net/rpc-channel.js:85:21
    at ClientRequest.onError (/Users/zork/Projects/Atom/atom-telegram/node_modules/telegram.link/node_modules/telegram-mt-node/lib/net/http-connection.js:122:13)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:288:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -2:00.9.0 project-plus:toggle-project-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:59.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:59.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:59 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:56.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -1:54.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:50.4.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -1:45.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:45.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:45.2.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14.3.0 command-palette:toggle (div.package-detail.panels-item)
  2x -0:12.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 atom-telegram:start (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "about",
      "archive-view",
      "autosave",
      "welcome",
      "terminal-plus",
      "expose",
      "linter-rubocop"
    ],
    "packagesWithKeymapsDisabled": [
      "tool-bar",
      "circle-ci",
      "ruby-syntax-replacer",
      "emmet",
      "merge-conflicts",
      "dash"
    ],
    "projectHome": "/Users/zork/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-telegram, v0.1.1
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.2
esc2, v0.0.0
file-icons, v1.6.18
imdone-atom, v1.3.27
language-docker, v1.1.6
last-cursor-position, v0.9.0
linter, v1.11.3
linter-docker, v0.1.2
linter-erb, v1.0.2
minimap, v4.19.0
project-plus, v0.7.0
react, v0.14.1
ruby-syntax-replacer, v0.5.1
symbol-gen, v1.0.0
synced-sidebar, v0.4.3
tool-bar, v0.3.0
vim-mode, v0.64.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by Morosko** [comment]
Looks like this error came from within the telegram API. Since when does it occur? Does it happen everytime you start atom-telegram?

**Comment by shemerey** [comment]
Yes that was weird issue, I just reinstall package and it's gone, I am closing it
